services:
  nginx:
    build: ./nginx
    ports:
      - "1024:443"
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress

  wordpress:
    build: ./wordpress
    volumes:
      - wordpress_data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpresspass
      WORDPRESS_DB_NAME: wordpress
    depends_on:
      - mariadb

  mariadb:
    build: ./mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpresspass

volumes:
  wordpress_data: